# @format

version: '3.8'
services:
  # fe-app:
  #   image: registry.cn-qingdao.aliyuncs.com/guang_guang/guang:aaa
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - nest-app
  #   restart: always
  #   networks:
  #     - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - mysql-container
      - redis-container
    restart: always
    networks:
      - common-network
  mysql-container:
    image: mysql:latest
    volumes:
      - /Users/zwj/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    restart: always
    networks:
      - common-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
  redis-container:
    image: redis:latest
    volumes:
      - /Users/zwj/redis-data:/data
    restart: always
    networks:
      - common-network
    ports:
      - '6379:6379'
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/zwj/minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: guang
      MINIO_ROOT_PASSWORD: dongdong
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
